const fixedNames = {
  TITLE: "Poketto",
  SHARE: "Share",
  YOUR: "Your",
  POKETTO: "Poketto",
  SITE_DESC: "すきなポケモンをシェアするアプリ",
  BTN_SHARE: "シェアする",
  BTN_EDIT: "編集する",
  BTN_LOOKUP_POKE: "ポケモンを見てみよう",
  BTN_SAVE: "保存する",
  BTN_LOGIN: "ログイン",
  BTN_LOGOUT: "ログアウト",
  BTN_GO_HOME: "ホームにいく",
  BTN_LOOK_UP_REGION: "地方をみる",
  BTN_GO_MYPAGE: "マイページ",
  BTN_BACK_MYPAGE: "マイページへ戻る",
  BTN_BYE: "お別れする😭",
  BTN_YES: "はい",
  BTN_BACK: "戻る",
  NON_NAME: "サトシさん",
  LABEL_NAME: "名前",
  LABEL_COMMENT: "コメント",
  PLACE_NAME: "名前を入力",
  PLACE_COMMENT: "コメントを入力",
  NON_POKE: "すきなポケモンの登録はありません",
  SHARE_POKE: "あなたのすきなポケモンをシェアしよう",
  SELECT_REGION: "すきな地方を選ぼう！",
  SELECT_POKE: "すきなポケモンを選ぼう！",
  FAVORITE_POKE_MAX: "すきなポケモン(6匹まで選べます)",
  FAVORITE_POKE: "すきなポケモン",
  USER_PAGE: "さんのページ",
  USER_PAGE_EDIT: "さんのページを編集",
  Q_USER_ACCOUNT_REMOVE: "アカウントを消しますか",
  UPDATE_SUCCESS: "更新しました",
  UPDATE_FAILED: "更新に失敗しました。再度お試しください",
  Q_REMOVE_POKE: "このポケモンを削除しますか",
  Q_SELECT_POKE: "このポケモンでよろしいですか",
  ERR_ALREADY_REGISTER: "既に登録されています",
  ERR_AREADY_MAX: "既に6匹まで登録されています",
  USER_LIKE_POKE: "さんのすきなポケモンは...\n",
  USER_POKE: "さんのすきなポケモン",
  ERR_MAX: "文字以内にしてください",
  ERR_ACCOUT_FAIL_REMOVE: "アカウントの削除に失敗しました",
  ERR_SOMETHING: "何らかのエラーが発生しました",
};

export default fixedNames;
